---
- name: 'Set github ssh keys {{ github_owner }}'
  hosts: base
  remote_user: root
  become_method: su
  vars:
    github_owner: 'github-user-dir'

  tasks:
    - name: Create ssh dir
      become: true
      become_user: '{{ github_owner }}'
      ansible.builtin.file:
        path: '/home/{{ github_owner }}/.ssh'
        state: directory
        mode: '0744'

    - name: Generate ssh key
      become: true
      become_user: '{{ github_owner }}'
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
      register: ssh_key

    - name: Add key
      ansible.builtin.uri:
        url: https://api.github.com/user/keys
        method: POST
        headers:
          Accept: 'application/vnd.github+json'
          Authorization: 'Bearer {{ github_api_key }}'
          X-GitHub-Api-Version: '2022-11-28'
        body_format: 'json'
        body: '{"title":"{{ github_owner }}","key":"{{ ssh_key.public_key }}"}'
        status_code:
          - 201
          - 422
