---
# defaults file for loop

# string to add as a prefix for role vars
loop_prefix: "{{ loop_role | default('', true) | lower | regex_replace('[^a-zA-Z]', '_') ~ '_' | regex_replace('^_') }}"

# options to apply to import_role
loop_allow_duplicates: "{{ omit }}"
loop_apply: "{{ omit }}"
loop_defaults_from: "{{ omit }}"
loop_handlers_from: "{{ omit }}"
loop_tasks_from: "{{ omit }}"
loop_vars_from: "{{ omit }}"
